### PR TITLE
Updated fastaai

### PR DESCRIPTION
**Pull request by KGerhardt**
All the changes I've been bugging you about for the last week.

### CODE REVIEW

**Comment by lmrodriguezr** [comment]
Please note that these changes break the compatibility with MiGA in several important ways:
- MiGA expects the executable `FastAAI/FastAAI` (within the folder and without `.py`)
- MiGA tests for versioned `python3` which is still the norm, since `python` usually refers to python 2
- MiGA uses the the flag `--input-paths` that has been removed from this version
- MiGA uses the `--all-vs-all` flag that has also been removed of this version

Is there any reason why all recent changes in the main repo were reversed?

**Comment by cruizperez** [comment]
I haven't reviewed these changes but I agree with Miguel in that the script needs to still be called FastAAI. The python version also needs to point to python3. I will check the other changes and make sure we are not breaking anything. I won't merge this PR yet.

**Comment by KGerhardt** [comment]
Why don't I take the fastaai in the folder and propagate my changes into that script. None should actually affect any moving parts.

**Comment by cruizperez** [comment]
You can also try doing that in the development branch so we can fully test it before merging it to the working master branch.

**Comment by KGerhardt** [comment]
That would be smart.

**Pull request closed without merging**
